<div class="swg swg-spinner" id="page-loader">
    <div class="spinner-box">
        <div class="spinner-message" hidden></div>
        <div class="spinner-symbol">
            <div class="loadingio-spinner-dual-ball-i4rbxz429u">
                <div class="ldio-ludptqkr5l">
                    <div></div>
                    <div></div>
                    <div></div>
                </div>
            </div>

            <style type="text/css">
                @keyframes ldio-ludptqkr5l-o
                {
                    0%    { opacity: 1; transform: translate(0 0) }
                    49.99% { opacity: 1; transform: translate(77.6px,0) }
                    50%    { opacity: 0; transform: translate(77.6px,0) }
                    100%    { opacity: 0; transform: translate(0,0) }
                }

                @keyframes ldio-ludptqkr5l
                {
                    0% { transform: translate(0,0) }
                    50% { transform: translate(77.6px,0) }
                    100% { transform: translate(0,0) }
                }

                .ldio-ludptqkr5l div
                {
                    position: absolute;
                    width: 77.6px;
                    height: 77.6px;
                    border-radius: 50%;
                    top: 58.199999999999996px;
                    left: 19.4px;
                }

                .ldio-ludptqkr5l div:nth-child(1)
                {
                    background: #018382;
                    animation: ldio-ludptqkr5l 1.923076923076923s linear infinite;
                    animation-delay: -0.9615384615384615s;
                }

                .ldio-ludptqkr5l div:nth-child(2)
                {
                    background: #bfc1c1;
                    animation: ldio-ludptqkr5l 1.923076923076923s linear infinite;
                    animation-delay: 0s;
                }

                .ldio-ludptqkr5l div:nth-child(3)
                {
                    background: #018382;
                    animation: ldio-ludptqkr5l-o 1.923076923076923s linear infinite;
                    animation-delay: -0.9615384615384615s;
                }

                .loadingio-spinner-dual-ball-i4rbxz429u
                {
                    width: 194px;
                    height: 194px;
                    display: inline-block;
                    overflow: hidden;
                    /*background: #f1f2f3;*/
                    background: transparent;
                }

                .ldio-ludptqkr5l
                {
                    width: 100%;
                    height: 100%;
                    position: relative;
                    transform: translateZ(0) scale(1);
                    backface-visibility: hidden;
                    transform-origin: 0 0; /* see note above */
                }

                .ldio-ludptqkr5l div { box-sizing: content-box; }
                /* generated by https://loading.io/ */
            </style>
        </div>
        <div class="spinner-countdown" hidden></div>
        <div class="spinner-progress" hidden>
            <div class="spinner-progress-value"></div>
        </div>
    </div>
    <div class="spinner-blackscreen" style="background-color: #737373;"></div>
</div>